### ISSUE TITLE
adding hacktoberfest tag in this repo

### ISSUE THREAD

**Issue by deauthe** [solana-developers/developer-bootcamp-2024#10]
The repository aims to bring in new developers in the solana space and adding this to the hacktoberfest will do just that. There are quite a few issues in the projects here (including some being completely empty). Why not add a small incentive to the devs out there to contribute more to this, create more examples, update the older ones. 
Love the effort to bringing everything practical to this one place anyways, cheers to the team !

**Comment by jacobcreech** [comment]
Appreciate the shoutout! We're actually not for examples in this repo, but I have added us elsewhere.
